GET http://localhost:3000

###

GET http://localhost:3000/books

###

POST http://localhost:3000/books
Content-Type: application/json

{
    "title":"New Book2",
    "author":"New Author2"
}

###

DELETE http://localhost:3000/books/1

###

PATCH  http://localhost:3000/books/1
Content-Type: application/json

{
    "title":"New Book Test"
}


###

PUT  http://localhost:3000/books/1
Content-Type: application/json

{
    "title":"New Book Test",
    "author":"New Author Test"
}

